# Generated by Django 4.0.4 on 2022-05-27 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSite',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.flatpage')),
                ('name', models.CharField(max_length=250)),
                ('logo', models.ImageField(upload_to='about_us')),
                ('favicon', models.ImageField(help_text='20px by 20px', null=True, upload_to='about_us', verbose_name='Small logo')),
                ('site_main_color', models.CharField(blank=True, max_length=15, null=True)),
                ('site_secondary_color', models.CharField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(help_text='separate multiple phone numbers with comma', max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=250)),
                ('facebook', models.CharField(blank=True, max_length=250, null=True)),
                ('twitter', models.CharField(blank=True, max_length=250, null=True)),
                ('instagram', models.CharField(blank=True, max_length=250, null=True)),
                ('youtube', models.CharField(blank=True, max_length=250, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=250, null=True)),
                ('social_image', models.ImageField(blank=True, help_text='Social media image', null=True, upload_to='about_us')),
                ('introduction', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Main Site',
            },
            bases=('flatpages.flatpage',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('headshot', models.ImageField(upload_to='author_headshots')),
                ('is_author', models.BooleanField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
